<?xml version="1.0"?>
<!-- Arm description for PhantomX Pincher arm -->
<robot name="phantomx_pincher_arm" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find phantomx_pincher_arm_description)/urdf/arm_hardware.xacro"/>

  <!--joints_vlimit pan_llimit pan_ulimit-->
  <xacro:macro name="phantomx_pincher_arm" params="parent color gripper_color *origin">
    <link name="arm_base_link"/>
    <joint name="arm_base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="arm_base_link"/>
    </joint>

    <!-- gripper_link -->
    <link name="gripper_link"/>
    <joint name="gripper_link_joint" type="revolute">
      <origin xyz="0 0 0.112" rpy="0 -1.57 0"/> <!--TODO: why does gripper_link have to be outside gripper tip for planning to work?-->
      <parent link="arm_wrist_flex_link"/>
      <child link="gripper_link"/>
      <limit effort="6" velocity="1" lower="-3.14" upper="3.14"/>
      <axis xyz="1 0 0"/>
    </joint>

    <!-- shoulder pan joint -->
    <dynamixel_AX12_fixed parent="arm_base_link" name="arm_shoulder_pan_servo">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </dynamixel_AX12_fixed>
    <bioloid_F3_revolute parent="arm_shoulder_pan_servo_link" name="arm_shoulder_pan" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
    </bioloid_F3_revolute>
    <transmission name="arm_shoulder_pan_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_shoulder_pan_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="arm_shoulder_pan_actuator">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- shoulder lift joint -->
    <dynamixel_AX12_fixed parent="arm_shoulder_pan_link" name="arm_shoulder_lift_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F4_revolute parent="arm_shoulder_lift_servo_link" name="arm_shoulder_lift" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${shoulder_llimit}" ulimit="${shoulder_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F4_revolute>
    <bioloid_F10_fixed parent="arm_shoulder_lift_link" name="arm_shoulder_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_shoulder_F10_0_link" name="arm_shoulder_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_shoulder_F10_1_link" name="arm_shoulder_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F3_fixed parent="arm_shoulder_F10_2_link" name="arm_shoulder_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </bioloid_F3_fixed>
    <transmission name="arm_shoulder_lift_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_shoulder_lift_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="arm_shoulder_lift_actuator">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- elbow joint -->
    <dynamixel_AX12_fixed parent="arm_shoulder_F3_0_link" name="arm_elbow_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F4_revolute parent="arm_elbow_flex_servo_link" name="arm_elbow_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${elbow_llimit}" ulimit="${elbow_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F4_revolute>
    <bioloid_F10_fixed parent="arm_elbow_flex_link" name="arm_elbow_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_elbow_F10_0_link" name="arm_elbow_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_elbow_F10_1_link" name="arm_elbow_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F3_fixed parent="arm_elbow_F10_2_link" name="arm_elbow_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </bioloid_F3_fixed>
    <transmission name="arm_elbow_flex_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_elbow_flex_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="arm_elbow_flex_actuator">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- wrist joint -->
    <dynamixel_AX12_fixed parent="arm_elbow_F3_0_link" name="arm_wrist_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F2_revolute parent="arm_wrist_flex_servo_link" name="arm_wrist_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${wrist_llimit}" ulimit="${wrist_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F2_revolute>
    <transmission name="arm_wrist_flex_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_wrist_flex_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="arm_wrist_flex_actuator">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  <!-- gripper -->
  <xacro:include filename="$(find phantomx_pincher_arm_description)/urdf/phantomx_pincher_gripper.xacro"/>

  <!--gazebo>
      <gripper name="gripper">
        <grasp_check>
          <attach_steps>5</attach_steps>
          <detach_steps>10</detach_steps>
          <min_contact_count>2</min_contact_count>
        </grasp_check>
      </gripper>
      <gripper_link>gripper_active_link</gripper_link>
      <palm_link>gripper_servo_link</palm_link>
  </gazebo-->

  </xacro:macro>

</robot>
